### ISSUE TITLE
How to activate a new syd address?

### ISSUE THREAD

**Issue by agmap** [VokezOfficial/systemd-mobile-wallet#1]
Hello,

how can I activate a new syd address.
I need 20 Syd to aktivate.
Can you help

**Comment by VokezOfficial** [comment]
Hello agmap,

If you post your address, we can send you 20 SYD to activate your address.

Let us know if you need anything else.

**Comment by agmap** [comment]
My address is:
rsL2FqQGufLfgGE9KRFYe7PHk5cSPBq7p6
But I need more SYD to do some things on SYDL, e.g. trustlines, buy and sell, ....
I would be happy when you could activate with 100000SYD.
When I need more SYD, where to buy some SYD?

**Comment by VokezOfficial** [comment]
Sent.

https://sydcharts.io/#/graph/CA20E89B8AE6A1D7B81B577BFA9EE34D56268B30227732FFE3897DA5A7DED91A

**Comment by agmap** [comment]
I need some more SYD. For adding trustline, active new account; open buy / sell orders, ...
Can you please send some more?

Is my account qualified for the Stipend of 120 #SYD?
